// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJH5w5rshZyHLRguuQX_e2fc-AmfbPilA',
    appId: '1:184561867400:android:501ca189e597d834ec5d3d',
    messagingSenderId: '184561867400',
    projectId: 'ieye-in',
    storageBucket: 'ieye-in.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1E_mrPCE5gBkVI3jfWSQteRIMjAccgxg',
    appId: '1:184561867400:ios:80e2c330a104ce93ec5d3d',
    messagingSenderId: '184561867400',
    projectId: 'ieye-in',
    storageBucket: 'ieye-in.firebasestorage.app',
    iosClientId: '184561867400-2o9f4pouck0t7op8ljj1hhb6qn4disb3.apps.googleusercontent.com',
    iosBundleId: 'in.ieye.ieye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1E_mrPCE5gBkVI3jfWSQteRIMjAccgxg',
    appId: '1:184561867400:ios:80e2c330a104ce93ec5d3d',
    messagingSenderId: '184561867400',
    projectId: 'ieye-in',
    storageBucket: 'ieye-in.firebasestorage.app',
    iosClientId: '184561867400-2o9f4pouck0t7op8ljj1hhb6qn4disb3.apps.googleusercontent.com',
    iosBundleId: 'in.ieye.ieye',
  );
}
